baseurl = "enigma.ic.unicamp.br/blog/"
title = "ENIGMA"
theme = "hugo-theme-cleanwhite"
languageCode = "pt-br"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = ""
  description = ""
  keyword = ""
  slogan = "" 

  image_404 = "img/404-bg.jpg"
  title_404 = ""

  showtoc = false

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # Sidebar settings
  sidebar_about_description = "O Enigma é uma entidade formada por alunos e alunas da Unicamp com o propósito de estudar privacidade, segurança e criptografia, além de outros assuntos relacionados."
  sidebar_avatar = "img/enigma_logo.png"

  featured_tags = false
  featured_condition_size = 2 
 
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true 
  email          = "enigmaunicamp@tutanota.com"
  telegram       = "https://t.me/enigmaunicamp"
  gitlab         = "https://gitlab.com/enigmaster"
 
  # [[params.bookmark_link]]
  # title =  "Martin Fowler"
  # href =  "https://martinfowler.com"
