baseURL = "https://enigma.ic.unicamp.br"
title   = "Enigma Unicamp"
languageCode = "en-us"
# publishDir = "docs"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
# googleAnalytics = ""

canonifyURLs = true
enableEmoji = true
publishDir = 'docs'

#
#[permalinks]
#  "/" = "/posts/:slug/"

[author]
  name = "Enigma UNICAMP"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)'], ['$$', '$$']]
    [markup.goldmark.renderer]
      unsafe = true




[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02/01/2006"
  dateformNumTime = "2006-01-02 15:04"
  subtitle  = ""
  math = true

  # Metadata mostly used in document's head
  description = "ENIGMA Unicamp"
  keywords = ""
  images = [""]

  # Home subtitle of the index page.
  homeSubtitle = """O Enigma, fundado em 2018 por alunos da UNICAMP, é uma organização estudantil dedicada à promoção do estudo da cybersegurança. Com uma equipe diversificada, o grupo oferece eventos, palestras e exercícios práticos, visando a democratização do conhecimento e a elevação da comunidade acadêmica no campo da cybersegurança."""

  # Enable theme toggle
  enableThemeToggle = true
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true
  # link local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []
  justifyContent = true

  [params.footer]
    rss = true
    bottomText = [
      "<a href=\"http://gohugo.io\">Hugo</a> template by <a href=\"https://github.com/rhazdon\">rhazdon</a>. Adapted by Andreis Purim."
    ]

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoText = "> $ cd /enigma@unicamp/"
    logoHomeLink = "/"
    # logoCursorColor = "#67a2c9"
    logoCursorPathname = true

  # Social icons
  # [[params.social]]
  #   name = "google-scholar"
  #   url  = "https://www.instagram.com/andreis.purim/"
  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/enigma.unicamp"
  [[params.social]]
    name = "github"
    url  = "https://github.com/Enigma-Unicamp"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/andreispurim/"
  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/@EnigmaUnicamp"

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 2
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
    weight     = 3
