baseurl = ""
title = "ENIGMA"
theme = "hugo-theme-cleanwhite"
languageCode = "pt-br"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = ""
  description = ""
  keyword = ""
  slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = ""

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false
  featured_condition_size = 2 
 
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true 
  email          = "youemail@gmail.com"
  #telegram TODO
 
  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesh中文网"
  href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
  title = "Awesome Service Mesh"
  href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
  title =  "Image Compression"
  href = "https://tinypng.com"
