## Basic Configuration
baseURL = "https://enigmaster.gitlab.io/blog/"
languageCode = "en-us"
title = "Enigma"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "ENIGMA"
    description = "ENIGMA"
    authorimage = "/img/enigma_logo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    telegram = "enigmaunicamp"
    email = "enigmaunicamp@tutanota.com"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"